# Generated by Django 5.2.3 on 2025-06-16 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, help_text="Date de naissance de l'élève.", null=True)),
                ('numero_etudiant', models.CharField(help_text="Numéro d'étudiant de l'élève.", max_length=20, unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_eleve': True}, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
