# Generated by Django 5.2.3 on 2025-06-16 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(help_text='Spécialité du formateur.', max_length=100)),
                ('experience', models.PositiveIntegerField(help_text="Années d'expérience du formateur.")),
                ('bio', models.TextField()),
                ('matricule', models.CharField(help_text='Matricule unique du formateur.', max_length=20, unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_formateur': True}, on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
