# Generated by Django 5.2.3 on 2025-06-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateurs', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité')),
                ('equipements', models.TextField(blank=True, verbose_name='Équipements')),
                ('batiment', models.CharField(max_length=50, verbose_name='Bâtiment')),
                ('etage', models.IntegerField(verbose_name='Étage')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'etage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20, verbose_name='Type de disponibilité')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formateurs.formateur', verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('objectifs', models.TextField(blank=True, verbose_name='Objectifs pédagogiques')),
                ('materiel_requis', models.TextField(blank=True, verbose_name='Matériel requis')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formateurs.formateur', verbose_name='Formateur')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation', verbose_name='Formation')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planning.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['date', 'heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('salle', 'date', 'heure_debut'), name='unique_booking'), models.UniqueConstraint(fields=('formateur', 'date', 'heure_debut'), name='unique_formateur_availability')],
            },
        ),
    ]
