# Generated by Django 5.2.3 on 2025-06-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('est_present', models.BooleanField(default=True, verbose_name='Est présent')),
                ('couleur', models.CharField(default='#28a745', max_length=7, verbose_name='Couleur')),
            ],
            options={
                'verbose_name': 'Statut de présence',
                'verbose_name_plural': 'Statuts de présence',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, help_text="Cochez si l'élève était présent", verbose_name='Présent')),
                ('date_verification', models.DateTimeField(auto_now=True, verbose_name='Date de vérification')),
                ('remarque', models.TextField(blank=True, help_text='Remarque éventuelle sur la présence/absence', verbose_name='Remarque')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='planning.cours', verbose_name='Cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['cours__date', 'cours__heure_debut', 'eleve__user__last_name'],
                'unique_together': {('cours', 'eleve')},
            },
        ),
    ]
